Computing average sentences for minors compared to adults

### Importing libraries

In [3]:
import pandas as pd

### Importing datasets

In [5]:
data_types = {
    "ID": str,
    "ST_IMPOSED_YR": str,
}

In [6]:
minors = pd.read_csv("data/obts/minors_analysissentences.csv", dtype = data_types)
adults = pd.read_csv("data/obts/adults_analysissentences.csv", dtype = data_types)

### filters for misdemeanors and felonies
minors = minors[minors["CT_CHARGE_LEVEL"].isin(["M", "F"])].reset_index(drop = True)
adults = adults[adults["CT_CHARGE_LEVEL"].isin(["M", "F"])].reset_index(drop = True)

### removes juvenile sanctions
minors = minors[minors["CT_ACTION_TAKEN"] != "K"].reset_index(drop = True)
adults = adults[adults["CT_ACTION_TAKEN"] != "K"].reset_index(drop = True)

### removes sentences with no confinement
minors = minors[minors["ST_DAYS"] != 0].reset_index(drop = True)
adults = adults[adults["ST_DAYS"] != 0].reset_index(drop = True)

C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_14952\1949578750.py:1: DtypeWarning: Columns (2,23,24,27,29,34,35,50) have mixed types. Specify dtype option on import or set low_memory=False.
  minors = pd.read_csv("data/obts/minors_analysissentences.csv", dtype = data_types)
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_14952\1949578750.py:2: DtypeWarning: Columns (2,23,24,26,27,29,34,35,38,40,41,48,49,50,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  adults = pd.read_csv("data/obts/adults_analysissentences.csv", dtype = data_types)

### Analyzing

#### Minors

In [9]:
minors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54809 entries, 0 to 54808
Data columns (total 58 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    54809 non-null  object
 1   MESSAGE_TYPE          54809 non-null  object
 2   OFF_TRAN_NO           54809 non-null  object
 3   COURT_DOCKET_NO       54809 non-null  object
 4   SEQUENCE_NO           54809 non-null  int64
 5   NO_OF_COUNTS          54809 non-null  int64
 6   COURT_DESIGNATOR      54809 non-null  object
 7   COUNTY                54809 non-null  int64
 8   ARREST_NAME           54809 non-null  object
 9   FINAL_NAME            54809 non-null  object
 10  SEX                   54765 non-null  object
 11  RACE                  54622 non-null  object
 12  BIRTH_DATE            54809 non-null  object
 13  INIT_ARREST_DT        54157 non-null  object
 14  CLERK_DT              54809 non-null  object
 15  OFFENSE_DT            54809 non-null  object
 16  CAPIAS_DT             30701 non-null  object
 17  REARREST_DT           19080 non-null  object
 18  AGE                   54809 non-null  float64
 19  PR_CHARGE_STATUS      54668 non-null  object
 20  PR_CHARGE_LEVEL       53754 non-null  object
 21  PR_CHARGE_DEGREE      53910 non-null  object
 22  PR_GEN_OFF_CHAR       54054 non-null  object
 23  PR_FLST_CHAP          53002 non-null  object
 24  PR_FLST_SECT          53002 non-null  object
 25  PR_FLST_SUBSECT       46347 non-null  object
 26  PR_FILING_DT          54074 non-null  float64
 27  PR_FINAL_DECISION_DT  53721 non-null  object
 28  PR_FINAL_ACTION       53006 non-null  object
 29  PR_COUNSEL_TYPE       52729 non-null  object
 30  CT_CHARGE_STATUS      54809 non-null  object
 31  CT_CHARGE_LEVEL       54809 non-null  object
 32  CT_CHARGE_DEGREE      54808 non-null  object
 33  CT_GEN_OFF_CHAR       54808 non-null  object
 34  CT_FLST_CHAP          54805 non-null  object
 35  CT_FLST_SECT          54805 non-null  object
 36  CT_FLST_SUBSECT       47498 non-null  object
 37  CT_DRUG_TYPE          43204 non-null  object
 38  CT_DECISION_DT        54809 non-null  float64
 39  CT_ACTION_TAKEN       54809 non-null  object
 40  CT_TRIAL_TYPE         54809 non-null  float64
 41  CT_FINAL_PLEA         54801 non-null  float64
 42  ST_IMPOSED_DT         54801 non-null  object
 43  ST_CONFINE            54809 non-null  float64
 44  ST_PART1              54809 non-null  float64
 45  ST_PART2              54809 non-null  float64
 46  ST_DAYS               54809 non-null  float64
 47  ST_CONFINE_TYPE       54809 non-null  object
 48  ST_CONFINE_LEN_SUSP   54809 non-null  float64
 49  ST_CREDIT_TIME        54809 non-null  float64
 50  ST_PROB_LEN           54809 non-null  object
 51  ST_COMM_LEN           54809 non-null  float64
 52  ST_FINE               54796 non-null  float64
 53  ST_COURT_COST         54796 non-null  float64
 54  ST_RESTITUTION        54809 non-null  float64
 55  ST_SENT_PROV          50959 non-null  object
 56  ST_SP_SENT_PROV       49119 non-null  object
 57  ST_IMPOSED_YR         54801 non-null  object
dtypes: float64(15), int64(3), object(40)
memory usage: 24.3+ MB

In [10]:
minors.head()

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_CONFINE_LEN_SUSP,ST_CREDIT_TIME,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR
0,480,N,108003062.0,012007CF003798XXXAXX,1,1,R,1,aa790a157211279dcdac28702346d17b8693ae03,aa790a157211279dcdac28702346d17b8693ae03,...,888888.0,185.0,0.0,888888.0,888888.88,728.00,888888.88,ENNNN,NNNNNNN,2009.0
1,922,N,102103423.0,012007CF005006XXXAXX,2,1,R,1,4213c8013b02dc0ca52392911cc7dae00fd4e899,4213c8013b02dc0ca52392911cc7dae00fd4e899,...,888888.0,183.0,0.0,888888.0,888888.88,738.00,888888.88,ENNNN,NNNNNNN,2009.0
2,923,N,102117699.0,012007CF005006XXXBXX,2,1,R,1,9a7ed269b70c071e4dd1424641c3c3a63424e9b7,9a7ed269b70c071e4dd1424641c3c3a63424e9b7,...,888888.0,45.0,10000.0,888888.0,888888.88,888888.88,888888.88,ENNNN,RNNNNNN,2012.0
3,1418,N,108005058.0,012007CF005512XXXDXX,1,1,R,1,809469b9e8e2323f7c3155d5dc8ae2408a075a8d,809469b9e8e2323f7c3155d5dc8ae2408a075a8d,...,888888.0,1133.0,0.0,888888.0,888888.88,551.00,888888.88,ENNNN,NNNNNNN,2011.0
4,2574,N,108000664.0,012008CF000224XXXAXX,1,1,R,1,cd32c542c8240ad02c0eb187435af4be8745bab3,cd32c542c8240ad02c0eb187435af4be8745bab3,...,888888.0,56.0,20000.0,888888.0,888888.88,728.00,888888.88,NNNNN,NNNNNNN,2008.0

In [11]:
minors["COURT_DESIGNATOR"].value_counts()

COURT_DESIGNATOR
R    51165
C     3644
Name: count, dtype: int64

##### Computing averages

In [13]:
### felonies and misdemeanors overall
avg_days = round(minors["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies + misdemeanors):", avg_days, "days and", avg_years, "years")

### felonies
felony = minors[minors["CT_CHARGE_LEVEL"] == "F"].reset_index(drop = True)
avg_days = round(felony["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies):", avg_days, "days and", avg_years, "years")

felony_capital = felony[felony["CT_CHARGE_DEGREE"] == "C"].reset_index(drop = True)
avg_days = round(felony_capital["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (capital felonies):", avg_days, "days and", avg_years, "years")

felony_life = felony[felony["CT_CHARGE_DEGREE"] == "L"].reset_index(drop = True)
avg_days = round(felony_life["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (life felonies):", avg_days, "days and", avg_years, "years")

felony_lifecap = felony[felony["CT_CHARGE_DEGREE"] == "P"].reset_index(drop = True)
avg_days = round(felony_lifecap["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree, punishable by life felonies):", avg_days, "days and", avg_years, "years")

felony_fst = felony[felony["CT_CHARGE_DEGREE"].isin(["F", "S", "T"])].reset_index(drop = True)
avg_days = round(felony_fst["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies, not life, capital or punishable by life):", avg_days, "days and", avg_years, "years")

felony_first = felony[felony["CT_CHARGE_DEGREE"] == "F"].reset_index(drop = True)
avg_days = round(felony_first["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree felonies):", avg_days, "days and", avg_years, "years")

felony_second = felony[felony["CT_CHARGE_DEGREE"] == "S"].reset_index(drop = True)
avg_days = round(felony_second["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (second-degree felonies):", avg_days, "days and", avg_years, "years")

felony_third = felony[felony["CT_CHARGE_DEGREE"] == "T"].reset_index(drop = True)
avg_days = round(felony_third["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (third-degree felonies):", avg_days, "days and", avg_years, "years")

### misdemeanors 
misd = minors[minors["CT_CHARGE_LEVEL"] == "M"].reset_index(drop = True)
avg_days = round(misd["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (misdemeanors):", avg_days, "days and", avg_years, "years")

misd_first = misd[misd["CT_CHARGE_DEGREE"] == "F"].reset_index(drop = True)
avg_days = round(misd_first["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree misdemeanors):", avg_days, "days and", avg_years, "years")

misd_second = misd[misd["CT_CHARGE_DEGREE"] == "S"].reset_index(drop = True)
avg_days = round(misd_second["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (second-degree misdemeanors):", avg_days, "days and", avg_years, "years")

Average sentence (felonies + misdemeanors): 1559 days and 4.3 years
Average sentence (felonies): 1865 days and 5.1 years
Average sentence (capital felonies): 21694 days and 59.4 years
Average sentence (life felonies): 5330 days and 14.6 years
Average sentence (first-degree, punishable by life felonies): 3614 days and 9.9 years
Average sentence (felonies, not life, capital or punishable by life): 1643 days and 4.5 years
Average sentence (first-degree felonies): 3644 days and 10.0 years
Average sentence (second-degree felonies): 1868 days and 5.1 years
Average sentence (third-degree felonies): 1133 days and 3.1 years
Average sentence (misdemeanors): 257 days and 0.7 years
Average sentence (first-degree misdemeanors): 316 days and 0.9 years
Average sentence (second-degree misdemeanors): 165 days and 0.5 years

#### Adults

In [15]:
adults.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3882100 entries, 0 to 3882099
Data columns (total 58 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    object
 1   MESSAGE_TYPE          object
 2   OFF_TRAN_NO           object
 3   COURT_DOCKET_NO       object
 4   SEQUENCE_NO           int64
 5   NO_OF_COUNTS          int64
 6   COURT_DESIGNATOR      object
 7   COUNTY                int64
 8   ARREST_NAME           object
 9   FINAL_NAME            object
 10  SEX                   object
 11  RACE                  object
 12  BIRTH_DATE            object
 13  INIT_ARREST_DT        object
 14  CLERK_DT              object
 15  OFFENSE_DT            object
 16  CAPIAS_DT             object
 17  REARREST_DT           object
 18  AGE                   float64
 19  PR_CHARGE_STATUS      object
 20  PR_CHARGE_LEVEL       object
 21  PR_CHARGE_DEGREE      object
 22  PR_GEN_OFF_CHAR       object
 23  PR_FLST_CHAP          object
 24  PR_FLST_SECT          object
 25  PR_FLST_SUBSECT       object
 26  PR_FILING_DT          object
 27  PR_FINAL_DECISION_DT  object
 28  PR_FINAL_ACTION       object
 29  PR_COUNSEL_TYPE       object
 30  CT_CHARGE_STATUS      object
 31  CT_CHARGE_LEVEL       object
 32  CT_CHARGE_DEGREE      object
 33  CT_GEN_OFF_CHAR       object
 34  CT_FLST_CHAP          object
 35  CT_FLST_SECT          object
 36  CT_FLST_SUBSECT       object
 37  CT_DRUG_TYPE          object
 38  CT_DECISION_DT        object
 39  CT_ACTION_TAKEN       object
 40  CT_TRIAL_TYPE         object
 41  CT_FINAL_PLEA         object
 42  ST_IMPOSED_DT         object
 43  ST_CONFINE            float64
 44  ST_PART1              float64
 45  ST_PART2              float64
 46  ST_DAYS               float64
 47  ST_CONFINE_TYPE       object
 48  ST_CONFINE_LEN_SUSP   object
 49  ST_CREDIT_TIME        object
 50  ST_PROB_LEN           object
 51  ST_COMM_LEN           float64
 52  ST_FINE               object
 53  ST_COURT_COST         object
 54  ST_RESTITUTION        float64
 55  ST_SENT_PROV          object
 56  ST_SP_SENT_PROV       object
 57  ST_IMPOSED_YR         object
dtypes: float64(7), int64(3), object(48)
memory usage: 1.7+ GB

In [16]:
adults.head()

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_CONFINE_LEN_SUSP,ST_CREDIT_TIME,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR
0,5,N,108009684,011999CT000044XXXAXX,1,1,C,1,f40c34e94f18211f599f6d33f100a177495d5885,f40c34e94f18211f599f6d33f100a177495d5885,...,888888,2.0,600.0,888888.0,888888.88,311.0,888888.88,NNNNN,NNNNNNN,2008.0
1,7,N,107215147,011999CT002017XXXAXX,1,1,C,1,8029268ab7aedea6af1ede51b9ddc954a96b3373,8029268ab7aedea6af1ede51b9ddc954a96b3373,...,888888,1.0,8888888.0,888888.0,888888.88,176.0,888888.88,NNNNN,NNNNNNN,2008.0
2,8,N,107204191,011999CT003705XXXAXX,1,1,C,1,b0beb66342d7638e225dacca947ba5906dd48bea,b0beb66342d7638e225dacca947ba5906dd48bea,...,888888,1.0,8888888.0,888888.0,888888.88,176.0,888888.88,NNNNN,NNNNNNN,2008.0
3,12,N,8888888888,012003CF000233XXXAXX,2,1,R,1,3dae823c33dbec00f80c24651bba60b65adf68d8,3dae823c33dbec00f80c24651bba60b65adf68d8,...,888888,1820.0,8888888.0,888888.0,888888.88,888888.88,888888.88,NNNNN,NNNNNNN,2008.0
4,55,N,108008146,012006CF001794XXXAXX,1,1,R,1,a9fa90c8354975ff6fb4d16df503e8ae43c21890,a9fa90c8354975ff6fb4d16df503e8ae43c21890,...,888888,643.0,8888888.0,888888.0,888888.88,888888.88,888888.88,NNNNN,NNNNNNN,2008.0

In [17]:
adults["COURT_DESIGNATOR"].value_counts()

COURT_DESIGNATOR
R    2532445
C    1349655
Name: count, dtype: int64

##### Computing averages

In [19]:
### felonies and misdemeanors overall
avg_days = round(adults["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies + misdemeanors):", avg_days, "days and", avg_years, "years")

### felonies
felony = adults[adults["CT_CHARGE_LEVEL"] == "F"].reset_index(drop = True)
avg_days = round(felony["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies):", avg_days, "days and", avg_years, "years")

felony_capital = felony[felony["CT_CHARGE_DEGREE"] == "C"].reset_index(drop = True)
avg_days = round(felony_capital["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (capital felonies):", avg_days, "days and", avg_years, "years")

felony_life = felony[felony["CT_CHARGE_DEGREE"] == "L"].reset_index(drop = True)
avg_days = round(felony_life["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (life felonies):", avg_days, "days and", avg_years, "years")

felony_lifecap = felony[felony["CT_CHARGE_DEGREE"] == "P"].reset_index(drop = True)
avg_days = round(felony_lifecap["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree, punishable by life felonies):", avg_days, "days and", avg_years, "years")

felony_fst = felony[felony["CT_CHARGE_DEGREE"].isin(["F", "S", "T"])].reset_index(drop = True)
avg_days = round(felony_fst["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (felonies, not life, capital or punishable by life):", avg_days, "days and", avg_years, "years")

felony_first = felony[felony["CT_CHARGE_DEGREE"] == "F"].reset_index(drop = True)
avg_days = round(felony_first["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree felonies):", avg_days, "days and", avg_years, "years")

felony_second = felony[felony["CT_CHARGE_DEGREE"] == "S"].reset_index(drop = True)
avg_days = round(felony_second["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (second-degree felonies):", avg_days, "days and", avg_years, "years")

felony_third = felony[felony["CT_CHARGE_DEGREE"] == "T"].reset_index(drop = True)
avg_days = round(felony_third["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (third-degree felonies):", avg_days, "days and", avg_years, "years")

### misdemeanors 
misd = adults[adults["CT_CHARGE_LEVEL"] == "M"].reset_index(drop = True)
avg_days = round(misd["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (misdemeanors):", avg_days, "days and", avg_years, "years")

misd_first = misd[misd["CT_CHARGE_DEGREE"] == "F"].reset_index(drop = True)
avg_days = round(misd_first["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (first-degree misdemeanors):", avg_days, "days and", avg_years, "years")

misd_second = misd[misd["CT_CHARGE_DEGREE"] == "S"].reset_index(drop = True)
avg_days = round(misd_second["ST_DAYS"].mean())
avg_years = round(avg_days/365, 1)
print("Average sentence (second-degree misdemeanors):", avg_days, "days and", avg_years, "years")

Average sentence (felonies + misdemeanors): 716 days and 2.0 years
Average sentence (felonies): 1278 days and 3.5 years
Average sentence (capital felonies): 32652 days and 89.5 years
Average sentence (life felonies): 9709 days and 26.6 years
Average sentence (first-degree, punishable by life felonies): 5980 days and 16.4 years
Average sentence (felonies, not life, capital or punishable by life): 1180 days and 3.2 years
Average sentence (first-degree felonies): 3861 days and 10.6 years
Average sentence (second-degree felonies): 2017 days and 5.5 years
Average sentence (third-degree felonies): 759 days and 2.1 years
Average sentence (misdemeanors): 172 days and 0.5 years
Average sentence (first-degree misdemeanors): 197 days and 0.5 years
Average sentence (second-degree misdemeanors): 121 days and 0.3 years