Merging basic, prosecutor, court and sentences databases for analysis

### Importing libraries

In [3]:
import pandas as pd

### Importing datasets

In [5]:
jr = pd.read_csv("data/obts/obts_basic_jr.csv")
sr = pd.read_csv("data/obts/obts_basic_sr.csv")

prosecutor = pd.read_csv("data/obts/obts_prosecutor.csv")
prosecutor.columns = prosecutor.columns.str.upper()

court = pd.read_csv("data/obts/obts_court.csv")
court.columns = court.columns.str.upper()

sentence_main = pd.read_csv("data/obts/sentence_main.csv")
sentence_other = pd.read_csv("data/obts/sentence_other.csv")
sentence_master = pd.read_csv("data/obts/sentence_master.csv")

C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  jr = pd.read_csv("data/obts/obts_basic_jr.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  sr = pd.read_csv("data/obts/obts_basic_sr.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:4: DtypeWarning: Columns (5,6,8,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  prosecutor = pd.read_csv("data/obts/obts_prosecutor.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:7: DtypeWarning: Columns (5,6,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  court = pd.read_csv("data/obts/obts_court.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:10: DtypeWarning: Columns (7,8,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sentence_main = pd.read_csv("data/obts/sentence_main.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:11: DtypeWarning: Columns (2,5,8,9,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  sentence_other = pd.read_csv("data/obts/sentence_other.csv")
C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_21176\4023445420.py:12: DtypeWarning: Columns (2,4,5,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  sentence_master = pd.read_csv("data/obts/sentence_master.csv")

### Merging for analysis on fixed duration sentences

#### Minors dataframe

In [8]:
minors = pd.merge(jr, prosecutor, on = "ID", how = "left")
minors = pd.merge(minors, court, on = "ID", how = "left")
minors = pd.merge(minors, sentence_main, on = "ID", how = "left")

minors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278795 entries, 0 to 278794
Data columns (total 58 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    278795 non-null  int64
 1   MESSAGE_TYPE          278795 non-null  object
 2   OFF_TRAN_NO           278795 non-null  object
 3   COURT_DOCKET_NO       278795 non-null  object
 4   SEQUENCE_NO           278795 non-null  int64
 5   NO_OF_COUNTS          278795 non-null  int64
 6   COURT_DESIGNATOR      278795 non-null  object
 7   COUNTY                278795 non-null  int64
 8   ARREST_NAME           278795 non-null  object
 9   FINAL_NAME            278795 non-null  object
 10  SEX                   276439 non-null  object
 11  RACE                  273320 non-null  object
 12  BIRTH_DATE            278795 non-null  object
 13  INIT_ARREST_DT        274971 non-null  object
 14  CLERK_DT              278782 non-null  object
 15  OFFENSE_DT            278795 non-null  object
 16  CAPIAS_DT             74337 non-null   object
 17  REARREST_DT           31925 non-null   object
 18  AGE                   278795 non-null  float64
 19  PR_CHARGE_STATUS      270904 non-null  object
 20  PR_CHARGE_LEVEL       225684 non-null  object
 21  PR_CHARGE_DEGREE      230379 non-null  object
 22  PR_GEN_OFF_CHAR       240064 non-null  object
 23  PR_FLST_CHAP          173169 non-null  object
 24  PR_FLST_SECT          173173 non-null  object
 25  PR_FLST_SUBSECT       149072 non-null  object
 26  PR_FILING_DT          241669 non-null  object
 27  PR_FINAL_DECISION_DT  229995 non-null  object
 28  PR_FINAL_ACTION       173806 non-null  object
 29  PR_COUNSEL_TYPE       217634 non-null  object
 30  CT_CHARGE_STATUS      263182 non-null  object
 31  CT_CHARGE_LEVEL       230431 non-null  object
 32  CT_CHARGE_DEGREE      234264 non-null  object
 33  CT_GEN_OFF_CHAR       240758 non-null  object
 34  CT_FLST_CHAP          177601 non-null  object
 35  CT_FLST_SECT          177593 non-null  object
 36  CT_FLST_SUBSECT       148063 non-null  object
 37  CT_DRUG_TYPE          197634 non-null  object
 38  CT_DECISION_DT        234471 non-null  object
 39  CT_ACTION_TAKEN       180892 non-null  object
 40  CT_TRIAL_TYPE         192901 non-null  object
 41  CT_FINAL_PLEA         181639 non-null  object
 42  ST_IMPOSED_DT         57868 non-null   object
 43  ST_CONFINE            60654 non-null   float64
 44  ST_PART1              60654 non-null   float64
 45  ST_PART2              60654 non-null   float64
 46  ST_DAYS               60654 non-null   float64
 47  ST_CONFINE_TYPE       59485 non-null   object
 48  ST_CONFINE_LEN_SUSP   60654 non-null   object
 49  ST_CREDIT_TIME        60654 non-null   object
 50  ST_PROB_LEN           59027 non-null   object
 51  ST_COMM_LEN           59027 non-null   float64
 52  ST_FINE               60641 non-null   object
 53  ST_COURT_COST         60641 non-null   object
 54  ST_RESTITUTION        60650 non-null   float64
 55  ST_SENT_PROV          54518 non-null   object
 56  ST_SP_SENT_PROV       52594 non-null   object
 57  ST_IMPOSED_YR         57868 non-null   float64
dtypes: float64(8), int64(4), object(46)
memory usage: 123.4+ MB

In [9]:
### drops irrelevant rows
minors = minors.dropna(subset = ["ST_DAYS"]).reset_index(drop = True)
minors = minors[minors["COURT_DESIGNATOR"] != "J"].reset_index(drop = True)

minors

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_CONFINE_LEN_SUSP,ST_CREDIT_TIME,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR
0,480,N,108003062,012007CF003798XXXAXX,1,1,R,1,aa790a157211279dcdac28702346d17b8693ae03,aa790a157211279dcdac28702346d17b8693ae03,...,888888,185.0,0.0,888888.0,888888.88,728.0,8.888889e+05,ENNNN,NNNNNNN,2009.0
1,922,N,102103423,012007CF005006XXXAXX,2,1,R,1,4213c8013b02dc0ca52392911cc7dae00fd4e899,4213c8013b02dc0ca52392911cc7dae00fd4e899,...,888888,183.0,0.0,888888.0,888888.88,738.0,8.888889e+05,ENNNN,NNNNNNN,2009.0
2,923,N,102117699,012007CF005006XXXBXX,2,1,R,1,9a7ed269b70c071e4dd1424641c3c3a63424e9b7,9a7ed269b70c071e4dd1424641c3c3a63424e9b7,...,888888,45.0,10000.0,888888.0,888888.88,888888.88,8.888889e+05,ENNNN,RNNNNNN,2012.0
3,1418,N,108005058,012007CF005512XXXDXX,1,1,R,1,809469b9e8e2323f7c3155d5dc8ae2408a075a8d,809469b9e8e2323f7c3155d5dc8ae2408a075a8d,...,888888,1133.0,0.0,888888.0,888888.88,551.0,8.888889e+05,ENNNN,NNNNNNN,2011.0
4,2574,N,108000664,012008CF000224XXXAXX,1,1,R,1,cd32c542c8240ad02c0eb187435af4be8745bab3,cd32c542c8240ad02c0eb187435af4be8745bab3,...,888888,56.0,20000.0,888888.0,888888.88,728.0,8.888889e+05,NNNNN,NNNNNNN,2008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60649,18330911,N,6601074574,662023CF000943CFAXMX,2,1,R,66,ca7811b2da45ead2f533971435dada9e54a6cad4,ca7811b2da45ead2f533971435dada9e54a6cad4,...,888888,5700,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
60650,18336601,N,6601072517,662023CT000127CTAXMX,1,1,C,66,cd189646d0868cbf5a3e4edebdefba4d2a5b3bd6,cd189646d0868cbf5a3e4edebdefba4d2a5b3bd6,...,200,0,600,0.0,75.0,249.75,8.888889e+08,N,N,2023.0
60651,18336894,N,6601072460,662023CT000343CTAXMX,1,1,C,66,7de48ae0b03a6e804eb14e94e3d249dca3a5e723,cd189646d0868cbf5a3e4edebdefba4d2a5b3bd6,...,200,0,600,0.0,75.0,249.75,8.888889e+08,N,N,2023.0
60652,18340433,N,6702007948,672023CF000305CFAXMX,1,1,R,67,3d773a6e23c8de8574c7597f65de67f79c88f8ba,3d773a6e23c8de8574c7597f65de67f79c88f8ba,...,888888,3000,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
60653,18340434,N,6702007948,672023CF000305CFAXMX,2,1,R,67,3d773a6e23c8de8574c7597f65de67f79c88f8ba,3d773a6e23c8de8574c7597f65de67f79c88f8ba,...,888888,3000,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0

#### Adults dataframe

In [11]:
adults = pd.merge(sr, prosecutor, on = "ID", how = "left")
adults = pd.merge(adults, court, on = "ID", how = "left")
adults = pd.merge(adults, sentence_main, on = "ID", how = "left")

adults.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17892425 entries, 0 to 17892424
Data columns (total 58 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   MESSAGE_TYPE          object
 2   OFF_TRAN_NO           object
 3   COURT_DOCKET_NO       object
 4   SEQUENCE_NO           int64
 5   NO_OF_COUNTS          int64
 6   COURT_DESIGNATOR      object
 7   COUNTY                int64
 8   ARREST_NAME           object
 9   FINAL_NAME            object
 10  SEX                   object
 11  RACE                  object
 12  BIRTH_DATE            object
 13  INIT_ARREST_DT        object
 14  CLERK_DT              object
 15  OFFENSE_DT            object
 16  CAPIAS_DT             object
 17  REARREST_DT           object
 18  AGE                   float64
 19  PR_CHARGE_STATUS      object
 20  PR_CHARGE_LEVEL       object
 21  PR_CHARGE_DEGREE      object
 22  PR_GEN_OFF_CHAR       object
 23  PR_FLST_CHAP          object
 24  PR_FLST_SECT          object
 25  PR_FLST_SUBSECT       object
 26  PR_FILING_DT          object
 27  PR_FINAL_DECISION_DT  object
 28  PR_FINAL_ACTION       object
 29  PR_COUNSEL_TYPE       object
 30  CT_CHARGE_STATUS      object
 31  CT_CHARGE_LEVEL       object
 32  CT_CHARGE_DEGREE      object
 33  CT_GEN_OFF_CHAR       object
 34  CT_FLST_CHAP          object
 35  CT_FLST_SECT          object
 36  CT_FLST_SUBSECT       object
 37  CT_DRUG_TYPE          object
 38  CT_DECISION_DT        object
 39  CT_ACTION_TAKEN       object
 40  CT_TRIAL_TYPE         object
 41  CT_FINAL_PLEA         object
 42  ST_IMPOSED_DT         object
 43  ST_CONFINE            float64
 44  ST_PART1              float64
 45  ST_PART2              float64
 46  ST_DAYS               float64
 47  ST_CONFINE_TYPE       object
 48  ST_CONFINE_LEN_SUSP   object
 49  ST_CREDIT_TIME        object
 50  ST_PROB_LEN           object
 51  ST_COMM_LEN           float64
 52  ST_FINE               object
 53  ST_COURT_COST         object
 54  ST_RESTITUTION        float64
 55  ST_SENT_PROV          object
 56  ST_SP_SENT_PROV       object
 57  ST_IMPOSED_YR         float64
dtypes: float64(8), int64(4), object(46)
memory usage: 7.7+ GB

In [12]:
### drops irrelevant rows
adults = adults.dropna(subset = ["ST_DAYS"]).reset_index(drop = True)

adults

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_CONFINE_LEN_SUSP,ST_CREDIT_TIME,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR
0,5,N,108009684,011999CT000044XXXAXX,1,1,C,1,f40c34e94f18211f599f6d33f100a177495d5885,f40c34e94f18211f599f6d33f100a177495d5885,...,888888,2.0,600.0,888888.0,888888.88,311.0,8.888889e+05,NNNNN,NNNNNNN,2008.0
1,7,N,107215147,011999CT002017XXXAXX,1,1,C,1,8029268ab7aedea6af1ede51b9ddc954a96b3373,8029268ab7aedea6af1ede51b9ddc954a96b3373,...,888888,1.0,8888888.0,888888.0,888888.88,176.0,8.888889e+05,NNNNN,NNNNNNN,2008.0
2,8,N,107204191,011999CT003705XXXAXX,1,1,C,1,b0beb66342d7638e225dacca947ba5906dd48bea,b0beb66342d7638e225dacca947ba5906dd48bea,...,888888,1.0,8888888.0,888888.0,888888.88,176.0,8.888889e+05,NNNNN,NNNNNNN,2008.0
3,12,N,8888888888,012003CF000233XXXAXX,2,1,R,1,3dae823c33dbec00f80c24651bba60b65adf68d8,3dae823c33dbec00f80c24651bba60b65adf68d8,...,888888,1820.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,2008.0
4,55,N,108008146,012006CF001794XXXAXX,1,1,R,1,a9fa90c8354975ff6fb4d16df503e8ae43c21890,a9fa90c8354975ff6fb4d16df503e8ae43c21890,...,888888,643.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,2008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4328594,18341463,N,6702008835,672023MM000399MMAXMX,2,1,C,67,5a953cf8536daa1a0f5e32a8445bb5bc0fbe08c8,5a953cf8536daa1a0f5e32a8445bb5bc0fbe08c8,...,888888,1100,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
4328595,18341464,N,6702008836,672023MM000400MMAXMX,1,1,C,67,9211085e390e96a57132545ab867b2210edbeec7,9211085e390e96a57132545ab867b2210edbeec7,...,888888,4100,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
4328596,18341465,N,6702008836,672023MM000400MMAXMX,2,1,C,67,9211085e390e96a57132545ab867b2210edbeec7,9211085e390e96a57132545ab867b2210edbeec7,...,888888,4100,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
4328597,18341477,N,6702008831,672024MM000001MMAXMX,1,1,C,67,07658dc92cc160a9ca377aa19c4c7bb196eb9980,07658dc92cc160a9ca377aa19c4c7bb196eb9980,...,888888,1400,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0
4328598,18341478,N,6702008319,672024MM000002MMAXMX,1,1,C,67,2777186fc8cc92b1461a6e6f4f12b196a8677cb9,2777186fc8cc92b1461a6e6f4f12b196a8677cb9,...,888888,5000,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,2024.0

#### Exporting dataframes

In [14]:
minors.to_csv("data/obts/minors_analysissentences.csv", index = False)
adults.to_csv("data/obts/adults_analysissentences.csv", index = False)

### Merging for analysis on life, death and juvenile sentences

#### Minors dataframe

In [17]:
minors = pd.merge(jr, prosecutor, on = "ID", how = "left")
minors = pd.merge(minors, court, on = "ID", how = "left")
minors = pd.merge(minors, sentence_other, on = "ID", how = "left")

minors = minors.dropna(subset = ["ST_CONFINE"]).reset_index(drop = True)
minors = minors[minors["COURT_DESIGNATOR"] != "J"].reset_index(drop = True)

minors

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR,ST_PART1,ST_PART2
0,69301,N,501175017,052008CF010557AXXXXX,1,1,R,5,e5e0c43689a43424cb4916741288172048e1a57c,5bc8b08329e2379320e54590c9034f7af12a74a7,...,8888888.0,0.0,888888888.0,351.0,888888888.0,8NNNN,NNNNNNN,2008.0,JUV,JUV
1,72184,N,501178478,052008CF014793BXXXXX,1,1,R,5,7337d4347d109442438077c6bdae59f2dee46e15,7337d4347d109442438077c6bdae59f2dee46e15,...,8888888.0,0.0,888888888.0,351.0,888888888.0,NNNNN,RNNNNNN,2021.0,LIFE,LIFE
2,72185,N,501178478,052008CF014793BXXXXX,2,1,R,5,7337d4347d109442438077c6bdae59f2dee46e15,7337d4347d109442438077c6bdae59f2dee46e15,...,8888888.0,0.0,888888888.0,888888888.0,888888888.0,NNNNN,NNNNNNN,2021.0,LIFE,LIFE
3,72186,N,501178478,052008CF014793BXXXXX,3,1,R,5,7337d4347d109442438077c6bdae59f2dee46e15,7337d4347d109442438077c6bdae59f2dee46e15,...,8888888.0,0.0,888888888.0,888888888.0,888888888.0,NNNNN,NNNNNNN,2021.0,LIFE,LIFE
4,85218,N,501192620,052008CF054210AXXXXX,1,1,R,5,06080cd8c2f54748344c2ac1b79084ee79c4ec0d,06080cd8c2f54748344c2ac1b79084ee79c4ec0d,...,8888888.0,0.0,888888888.0,451.0,888888888.0,NNNNN,NNNNNNN,2019.0,LIFE,LIFE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15951208,N,4701066991,472021CF000326CFAXMX,2,1,R,47,579ddba5687b1ab31b526b36a6942c8fac69e33b,0e98392d9a3577631bbd621b9357ee9d994347c1,...,8888888.0,0.0,888888888.0,888888888.0,888888888.0,4UOT,N,2021.0,JUV,JUV
235,16237607,N,8888888888,552021CF000825XXAXMX,1,1,R,55,af8eed09008a317fafefc1c3e16c6c9fa54392c7,af8eed09008a317fafefc1c3e16c6c9fa54392c7,...,8888888.0,0.0,0.0,0.0,0.0,NNNNN,G,2023.0,LIFE,LIFE
236,17716650,N,3101148695,312020CF000598BXXXXX,8,1,R,31,4c0383e878444423926e536dacb13ebf27e587c9,4c0383e878444423926e536dacb13ebf27e587c9,...,8888888.0,0.0,0.0,0.0,0.0,NNNNN,NNNNNNN,2023.0,LIFE,LIFE
237,18233737,N,8888888888,582023CF010268XXXANC,1,1,R,58,8fca470e2322c59cbe2b08390dfb6baed546e1a6,8fca470e2322c59cbe2b08390dfb6baed546e1a6,...,8888888.0,0.0,0.0,0.0,0.0,NNNNN,NNNNNNN,2023.0,JUV,JUV
238,18233738,N,8888888888,582023CF010268XXXANC,2,1,R,58,8fca470e2322c59cbe2b08390dfb6baed546e1a6,8fca470e2322c59cbe2b08390dfb6baed546e1a6,...,8888888.0,0.0,0.0,0.0,0.0,NNNNN,NNNNNNN,2023.0,JUV,JUV

#### Adults dataframe

In [19]:
adults = pd.merge(sr, prosecutor, on = "ID", how = "left")
adults = pd.merge(adults, court, on = "ID", how = "left")
adults = pd.merge(adults, sentence_other, on = "ID", how = "left")

adults = adults.dropna(subset = ["ST_CONFINE"]).reset_index(drop = True)

adults

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR,ST_PART1,ST_PART2
0,5022,N,108003372,012008CF001606XXXAXX,1,1,R,1,2c2277369d81120c676c85b0c93f4c3497fe5dc3,2c2277369d81120c676c85b0c93f4c3497fe5dc3,...,0.0,0.0,888888888.0,888888888.0,888888888.0,NNNNN,NNNNNNN,2011.0,DEATH,DEATH
1,5023,N,14246574,012008CF001606XXXAXX,2,1,R,1,2c2277369d81120c676c85b0c93f4c3497fe5dc3,2c2277369d81120c676c85b0c93f4c3497fe5dc3,...,0.0,0.0,888888888.0,551.0,888888888.0,NNNNN,NNNNNNN,2009.0,DEATH,DEATH
2,5787,N,108011280,012008CF002070XXXAXX,1,1,R,1,88a33a0288c01661a776e59a776b4239cc27c4bb,88a33a0288c01661a776e59a776b4239cc27c4bb,...,0.0,0.0,888888888.0,1023.0,888888888.0,NNNNN,NNNNNNN,2012.0,DEATH,DEATH
3,5788,N,8888888888,012008CF002070XXXAXX,2,1,R,1,88a33a0288c01661a776e59a776b4239cc27c4bb,88a33a0288c01661a776e59a776b4239cc27c4bb,...,0.0,0.0,888888888.0,1023.0,888888888.0,NNNNN,NNNNNNN,2012.0,DEATH,DEATH
4,9080,N,108011148,012008CF004088XXXAXX,1,1,R,1,019f8387d2c96f6f1fc69d06d4329767061cb47c,019f8387d2c96f6f1fc69d06d4329767061cb47c,...,0.0,0.0,888888888.0,1174.0,888888888.0,NNNNN,INNNNNN,2012.0,DEATH,DEATH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6727,18225470,N,5801289895,582021CF009387XXXANC,12,1,R,58,a0c1a02f582b9b2af2574eda0d2ef10e031b5cac,a0c1a02f582b9b2af2574eda0d2ef10e031b5cac,...,8888888.0,0.0,0.0,302.0,0.0,NNNNN,I,2023.0,LIFE,LIFE
6728,18225471,N,8888888888,582021CF009387XXXANC,48,1,R,58,a0c1a02f582b9b2af2574eda0d2ef10e031b5cac,a0c1a02f582b9b2af2574eda0d2ef10e031b5cac,...,8888888.0,0.0,0.0,302.0,0.0,NNNNN,I,2023.0,LIFE,LIFE
6729,18225506,N,5801304201,582022CF001133XXXANC,4,1,R,58,26e8fe8b3ca0c40be7f50d613d19ba746479baec,26e8fe8b3ca0c40be7f50d613d19ba746479baec,...,8888888.0,0.0,0.0,0.0,0.0,NNNNN,NNNNNNN,2023.0,LIFE,LIFE
6730,18282134,N,8888888888,642022CF304522XXXADB,2,1,R,64,19733cb0d135151a9a3c1102b339d17587be28ec,d55f6df2e4165499f9db21d9c8774a9268e88959,...,8888888.0,0.0,888888888.0,888888888.0,888888888.0,T,NNNNNNN,2023.0,LIFE,LIFE
6731,18282460,N,8888888888,642022CF305864XXXADB,8,1,R,64,b4d0129efe4a69fa9aa8a28f1ef52593f9d77445,58f1f0358e7063146f53e80a8c4b606855d4e0df,...,8888888.0,0.0,888888888.0,888888888.0,888888888.0,T,NNNNNNN,2023.0,LIFE,LIFE

#### Exporting dataframes

In [21]:
minors.to_csv("data/obts/minors_othersentences.csv", index = False)
adults.to_csv("data/obts/adults_othersentences.csv", index = False)

### Merging for master minors database

In [23]:
minors = pd.merge(jr, prosecutor, on = "ID", how = "left")
minors = pd.merge(minors, court, on = "ID", how = "left")
minors = pd.merge(minors, sentence_master, on = "ID", how = "left")

minors = minors[minors["COURT_DESIGNATOR"] != "J"].reset_index(drop = True)

minors

,ID,MESSAGE_TYPE,OFF_TRAN_NO,COURT_DOCKET_NO,SEQUENCE_NO,NO_OF_COUNTS,COURT_DESIGNATOR,COUNTY,ARREST_NAME,FINAL_NAME,...,ST_CONFINE_LEN_SUSP,ST_CREDIT_TIME,ST_PROB_LEN,ST_COMM_LEN,ST_FINE,ST_COURT_COST,ST_RESTITUTION,ST_SENT_PROV,ST_SP_SENT_PROV,ST_IMPOSED_YR
0,48,N,8888888888,012005CF005485XXXAXX,1,1,R,1,0377b33bdb918406b8547a8efb0b054ba21e0a9b,0377b33bdb918406b8547a8efb0b054ba21e0a9b,...,888888,0.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,NaN
1,49,N,8888888888,012005CF005485XXXAXX,2,1,R,1,0377b33bdb918406b8547a8efb0b054ba21e0a9b,0377b33bdb918406b8547a8efb0b054ba21e0a9b,...,888888,0.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,NaN
2,50,N,8888888888,012005CF005485XXXAXX,3,1,R,1,0377b33bdb918406b8547a8efb0b054ba21e0a9b,0377b33bdb918406b8547a8efb0b054ba21e0a9b,...,888888,0.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,NaN
3,51,N,8888888888,012005CF005485XXXAXX,4,1,R,1,0377b33bdb918406b8547a8efb0b054ba21e0a9b,0377b33bdb918406b8547a8efb0b054ba21e0a9b,...,888888,0.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,NaN
4,290,N,8888888888,012007CF002605XXXAXX,1,1,R,1,5cb02c8ff9cd28b3c9e88355a67fea53514246ab,5cb02c8ff9cd28b3c9e88355a67fea53514246ab,...,888888,0.0,8888888.0,888888.0,888888.88,888888.88,8.888889e+05,NNNNN,NNNNNNN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278790,18340966,N,8888888888,672023IN000114INAXMX,1,1,C,67,fd6243c34fc918a6455d775d98eb78eaaa3daae9,fd6243c34fc918a6455d775d98eb78eaaa3daae9,...,888888,0,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,NaN
278791,18340967,N,8888888888,672023IN000115INAXMX,1,1,C,67,9b55e388296426b9247b77aaf6c70316b287e5e6,9b55e388296426b9247b77aaf6c70316b287e5e6,...,888888,0,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,NaN
278792,18340968,N,8888888888,672023IN000116INAXMX,1,1,C,67,9b55e388296426b9247b77aaf6c70316b287e5e6,9b55e388296426b9247b77aaf6c70316b287e5e6,...,888888,0,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,NaN
278793,18340969,N,8888888888,672023IN000117INAXMX,1,1,C,67,9b55e388296426b9247b77aaf6c70316b287e5e6,9b55e388296426b9247b77aaf6c70316b287e5e6,...,888888,0,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,NaN
278794,18340974,N,8888888888,672023IN000122INAXMX,1,1,C,67,36bf51f3bdbf11b2b3e89b3316d7c4c7e86a83ff,36bf51f3bdbf11b2b3e89b3316d7c4c7e86a83ff,...,888888,0,8888888,0.0,888888888.0,888888888.0,8.888889e+08,N,N,NaN

#### Exporting dataframe

In [25]:
minors.to_csv("data/obts/minors_sentences_master.csv", index = False)