Checking datatypes and dataset arrangements

### Importing libraries

In [1]:
import pandas as pd

### Importing datasets

In [2]:
obts_court = pd.read_csv("data/obts/obts_court.csv")
obts_court.columns = obts_court.columns.str.upper()

obts_court

C:\Users\sdasgupta\AppData\Local\Temp\ipykernel_8328\1765955256.py:1: DtypeWarning: Columns (5,6,9,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  obts_court = pd.read_csv("data/obts/obts_court.csv")

,ID,CT_CHARGE_STATUS,CT_CHARGE_LEVEL,CT_CHARGE_DEGREE,CT_GEN_OFF_CHAR,CT_FLST_CHAP,CT_FLST_SECT,CT_FLST_SUBSECT,CT_DRUG_TYPE,CT_DECISION_DT,CT_ACTION_TAKEN,CT_TRIAL_TYPE,CT_FINAL_PLEA
0,5,S,M,S,N,322.0,34,2,N,20080811.0,G,1.0,3.0
1,6,S,M,S,N,322.0,34,2,N,20080709.0,G,1.0,3.0
2,7,S,M,S,N,322.0,03,1,N,20080218.0,G,1.0,3.0
3,8,S,M,S,N,322.0,03,1,N,20080128.0,G,1.0,3.0
4,12,S,F,T,N,784.0,021,NaN,N,20080813.0,G,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17440642,18341482,N,N,N,N,NaN,NaN,NaN,N,0,NaN,NaN,NaN
17440643,18341483,N,N,N,N,NaN,NaN,NaN,N,0,NaN,NaN,NaN
17440644,18341484,N,N,N,N,NaN,NaN,NaN,N,0,NaN,NaN,NaN
17440645,18341485,N,N,N,N,NaN,NaN,NaN,N,0,NaN,NaN,NaN
17440646,18341486,N,N,N,N,NaN,NaN,NaN,N,0,NaN,NaN,NaN

In [3]:
obts_court.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17440647 entries, 0 to 17440646
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   ID                int64
 1   CT_CHARGE_STATUS  object
 2   CT_CHARGE_LEVEL   object
 3   CT_CHARGE_DEGREE  object
 4   CT_GEN_OFF_CHAR   object
 5   CT_FLST_CHAP      object
 6   CT_FLST_SECT      object
 7   CT_FLST_SUBSECT   object
 8   CT_DRUG_TYPE      object
 9   CT_DECISION_DT    object
 10  CT_ACTION_TAKEN   object
 11  CT_TRIAL_TYPE     object
 12  CT_FINAL_PLEA     object
dtypes: int64(1), object(12)
memory usage: 1.7+ GB

In [4]:
obts_court["CT_CHARGE_LEVEL"].value_counts()

CT_CHARGE_LEVEL
M    6319056
N    3734571
F    3024627
I     664425
L     363445
C     334185
3         48
X         33
S         32
2         24
5         18
Q          9
`          3
R          3
U          2
4          2
Y          2
+          1
J          1
Name: count, dtype: int64

In [5]:
obts_court["CT_CHARGE_DEGREE"].value_counts()

CT_CHARGE_DEGREE
N    5329332
F    3548514
S    3444600
T    2284487
L      17554
P      14740
C       6179
M          1
Name: count, dtype: int64